const gameData = [
    {
        id: 1,
        isGreen: false,
        isUFO: true,
        point: 10,
        pointArr: [0],
    },
    {
        id: 2,
        isGreen: false,
        isUFO: false,
        isChoosen: false,
        displayLeftArrow: false,
        displayRightArrow: false,
        point: 5,
        pointArr: [1, 2, 3, 4, 5],
        // point: 0,
        // pointArr: [],
    },
    {
        id: 3,
        isGreen: false,
        isUFO: false,
        isChoosen: false,
        displayLeftArrow: false,
        displayRightArrow: false,
        point: 5,
        pointArr: [1, 2, 3, 4, 5],
        // point: 0,
        // pointArr: [],
    },
    {
        id: 4,
        isGreen: false,
        isUFO: false,
        isChoosen: false,
        displayLeftArrow: false,
        displayRightArrow: false,
        point: 5,
        pointArr: [1, 2, 3, 4, 5],
        // point: 1,
        // pointArr: [1],
        // point: 0,
        // pointArr: [],
    },
    {
        id: 5,
        isGreen: false,
        isUFO: false,
        isChoosen: false,
        displayLeftArrow: false,
        displayRightArrow: false,
        point: 5,
        pointArr: [1, 2, 3, 4, 5],
        // point: 0,
        // pointArr: [],
    },
    {
        id: 6,
        isGreen: false,
        isUFO: false,
        isChoosen: false,
        displayLeftArrow: false,
        displayRightArrow: false,
        point: 5,
        pointArr: [1, 2, 3, 4, 5],
        // point: 1,
        // pointArr: [1],
    },
    {
        id: 7,
        isGreen: false,
        isUFO: false,
        isChoosen: false,
        displayLeftArrow: false,
        displayRightArrow: false,
        point: 5,
        pointArr: [1, 2, 3, 4, 5],
        // point: 0,
        // pointArr: [],
    },
    {
        id: 8,
        isGreen: false,
        isUFO: false,
        isChoosen: false,
        displayLeftArrow: false,
        displayRightArrow: false,
        point: 5,
        pointArr: [1, 2, 3, 4, 5],
    },
    {
        id: 9,
        isGreen: false,
        isUFO: false,
        isChoosen: false,
        displayLeftArrow: false,
        displayRightArrow: false,
        point: 5,
        pointArr: [1, 2, 3, 4, 5],
        // point: 0,
        // pointArr: [],
    },
    {
        id: 10,
        isGreen: false,
        isUFO: false,
        isChoosen: false,
        displayLeftArrow: false,
        displayRightArrow: false,
        point: 5,
        pointArr: [1, 2, 3, 4, 5],
        // point: 0,
        // pointArr: [],
    },
    {
        id: 11,
        isGreen: false,
        isUFO: false,
        isChoosen: false,
        displayLeftArrow: false,
        displayRightArrow: false,
        point: 5,
        pointArr: [1, 2, 3, 4, 5],
    },
    {
        id: 12,
        isGreen: false,
        isUFO: true,
        point: 10,
        pointArr: [0],
    },
];

export default gameData;
